/**
 * @file test_crypt.c
 * @author Petr Hanzlik <Petr.Hanzlik@cesnet.cz>
 * @brief libnetconf2 tests - internal password hashing
 *
 * @copyright
 * Copyright (c) 2026 CESNET, z.s.p.o.
 *
 * This source code is licensed under BSD 3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://opensource.org/licenses/BSD-3-Clause
 */

#define _GNU_SOURCE

#include <stdlib.h>
#include <string.h>

#include <cmocka.h>

#include "compat.h"
#include "crypt_p.h"

/* complete "$6$" hash of the password "hello" with the salt "abcdefghijklmnop", used by several tests */
#define TEST_HASH_SHA512_HELLO \
    "$6$abcdefghijklmnop$vRqpf9WzVv13MKJy4hd5jALhNQnt4y0RZsj0MrdHWdwA8G8gihD6oj69IwfuemaVekHG0M6jA5HNgthaIaLRR/"

/**
 * @brief Reference vectors for all the supported schemes.
 *
 * The expected values were generated by the reference glibc crypt_r(3)
 * implementation, called with the exact password and setting of each vector:
 *
 *   struct crypt_data data = {0};
 *   crypt_r(password, setting, &data);
 *
 * The vectors with a salt longer than 8 ("$1$") or 16 ("$5$"/"$6$")
 * characters verify the salt truncation, crypt_r(3) truncates the salts the
 * same way. All the salts (and digests) are within the crypt base64
 * alphabet [a-zA-Z0-9./].
 */
static const struct test_vector {
    const char *setting;  /* "$<id>$[rounds=N$]<salt>$" */
    const char *password; /* clear-text password */
    const char *expected; /* complete hash */
} test_vectors[] = {
    /* MD5-crypt */
    {"$1$abc$", "hello", "$1$abc$jWy0FsfCoVBK.I85XpXf30"},
    {"$1$abc$", "", "$1$abc$Or2rbeUYTvt12aiVzMuS/."},
    {"$1$abc$", "0123456789abcdef", "$1$abc$RWqMNvoz3MlAm/dUNBly11"},
    {"$1$abc$", "0123456789abcdef7", "$1$abc$UoisR6zt/vyX.GVBejn/s/"},
    {"$1$abc$", "0123456789abcdef78", "$1$abc$AiQKSpZM70XZD/J5cq1zo0"},
    {"$1$abc$", "0123456789012345678901234567890123456789012345678901234567890123", "$1$abc$o6f5nh6VgFk5PuY00GZ4q."},
    {"$1$abc$", "h\xc3\xa9llo", "$1$abc$olqAE9a3sVQf1DzmPrTaz1"},
    {"$1$abcdefgh$", "hello", "$1$abcdefgh$rwnEbRiN0agqVgZBovWNQ/"},
    /* the salt of "$1$" is truncated to 8 characters */
    {"$1$abcdefghijklmnop$", "hello", "$1$abcdefgh$rwnEbRiN0agqVgZBovWNQ/"},
    {"$1$verylongsaltvaluewayover16chars$", "hello", "$1$verylong$G.EmESvPcN/dfh2zVVLo4."},
    {"$1$", "hello", "$1$$/PWPe740uvaQxKzRH.Zxj1"},
    {"$1$", "", "$1$$qRPK7m23GJusamGpoGLby/"},

    /* SHA-256-crypt */
    {"$5$abc$", "hello", "$5$abc$W6SISEcmf6GfVdGFK0lGBXz2NPDhGZ.FBBMOz418YA7"},
    {"$5$abc$", "0123456789abcdef", "$5$abc$YpspK6zwM3epwlxYlNbhj1uz8M0olliID/rZqdtH7uC"},
    {"$5$abc$", "0123456789abcdef7", "$5$abc$g.imuXJ8IzZ8mWpgqnfFLnjgo1XuwbBvNqfBSIXDZ1/"},
    {"$5$abc$", "0123456789abcdef78", "$5$abc$K5aj4AYNi23Mtsp4uB.Tuuxxgqn6L6g4XkK/Utg1q.4"},
    {"$5$abc$", "0123456789012345678901234567890123456789012345678901234567890123", "$5$abc$fICUW/9OYTl38W5To0V79TTVmJMhLE6YYvM9Qs9uAk4"},
    {"$5$abc$", "h\xc3\xa9llo", "$5$abc$inGrvBqHz8uZkN.P/YPvmi1zgtyg/YXaTiIUXx6HTK0"},
    {"$5$abcdefgh$", "hello", "$5$abcdefgh$UUoko/Tf0b.8LrDH6BE28ZvVbc7xd//GfzsD0NKugU7"},
    /* the salt of "$5$"/"$6$" is truncated to 16 characters */
    {"$5$abcdefghijklmnop$", "hello", "$5$abcdefghijklmnop$PWitSpu2soJsfZ6ATsTxeTHC527GEr8VkIcYoKnV6G/"},
    {"$5$abcdefghijklmnopq$", "hello", "$5$abcdefghijklmnop$PWitSpu2soJsfZ6ATsTxeTHC527GEr8VkIcYoKnV6G/"},
    {"$5$verylongsaltvaluewayover16chars$", "hello", "$5$verylongsaltvalu$Efvl8TQO5e9pnzw6o64VsLpL3QQT9VQpZfJI198GR61"},
    /* "rounds=" specification */
    {"$5$rounds=1000$abcdefghijklmnop$", "hello", "$5$rounds=1000$abcdefghijklmnop$WrXWnj4kGA329xgo6OuYgg4dCUBFRerEyEW8GtoN6I5"},
    {"$5$rounds=10000$abcdefghijklmnop$", "hello", "$5$rounds=10000$abcdefghijklmnop$gakfHbxNcYmu8/VVGCdhagYkdMmRhzRqQyQhHYWi9k7"},
    {"$5$", "hello", "$5$$TCRu/ts4Npu8OJyeWy2WnUHCe/6bKVMSi0sROUrPh48"},

    /* SHA-512-crypt */
    {"$6$abc$", "hello", "$6$abc$34O8oRzThM7onc3iRQAcdWBv2H/sMGJlnsnG6uIkasTEvQkG9apXR/oBhPpqIepkul8wg.bf4wxoel67eJND./"},
    {"$6$abcdefgh$", "hello", "$6$abcdefgh$bp46WUxDu2cphMRE0PvVJlqas2imuSq186YS793XKfmqn9XUEL17HECskUTZInaNigNndLLYc7A6yWBmFEFn3/"},
    /* '.' and '/' are valid salt characters */
    {"$6$ab.cd/ef$", "hello", "$6$ab.cd/ef$sV4BC2Kqe0jWhdQioxhq0MCijtPO/TSfuBdFg63JbMMpm6iDkLX8LEnLB5PSaFMJp13pjvWAH46wN.vvu6z45."},
    {"$6$abcdefghijklmnop$", "hello", TEST_HASH_SHA512_HELLO},
    {"$6$abcdefghijklmnop$", "0123456789abcdef", "$6$abcdefghijklmnop$WQAzULv0Ukk44nlNhVKoNi3QBj9GOrOUYqHJK7K/cen5os5qmscMn/GK9p68EawC37X.H..TBeQL1We6POnYI0"},
    {"$6$abcdefghijklmnop$", "h\xc3\xa9llo", "$6$abcdefghijklmnop$BjRFgpCnoEl8cfIQCpEqVHEVCTsjvYInzBjb6J.KLIXKs8JGYiDPELluRy8z3LVO5wmWST41bCrlm6zcGCUgM1"},
    {"$6$verylongsaltvaluewayover16chars$", "hello", "$6$verylongsaltvalu$6hTjPqyUed7wu3zyqaBUB.p0vw6sqLZhMoYW7x7jQqlBk2lFs0rcfDlx1HP14WHuUz7ISsstvqNHsf65BHACJ0"},
    /* "rounds=" specification */
    {"$6$rounds=1000$abcdefghijklmnop$", "hello", "$6$rounds=1000$abcdefghijklmnop$GsvqqORKveGP9eM50U7hoZ2RaYgO9vXD6Ludjc08Zj00u1Yk0AHH7rzYh6a.UMZ62y6Z7G/DVTJslcByAE9NI/"},
    {"$6$rounds=10000$abcdefghijklmnop$", "hello", "$6$rounds=10000$abcdefghijklmnop$9sNcVihoH1.aunYOPqyb.bKPu4qE59NF9J2D9VKvsbdqNWuzqKAsS7bzjInP5HL0DXOwpM/6/J6FYcGDV4MNo/"},
    {"$6$abcdefghijklmnop$", "", "$6$abcdefghijklmnop$6.vC8ffobuN7AxcHvesxeeksF2DXFfpYyFt3PFU8pYpEQPhWFSN7hwaUQRfHg/LkfB3jIPEitUcU7ZTqjaQUp1"},
    {"$6$", "hello", "$6$$8E8LfwilfZ5LGh4IJH.CRzu9SqEBIk11xcvH1HL2h7nPXSOL41SgqNeOe1lSKb0D0r.6tMA2NFig55Fr3bO1V0"},
};

/**
 * @brief Create a hash for the given password and setting.
 *
 * @param[in] password Password.
 * @param[in] setting Setting "$<id>$[rounds=N$]<salt>$".
 * @param[out] out Output buffer.
 * @param[out] out_len Capacity of @p out including the terminating NUL.
 * @return nc_crypt() return value.
 */
static int
test_crypt_create(const char *password, const char *setting, char *out, size_t out_len)
{
    struct nc_crypt c;

    memset(&c, 0, sizeof c);
    c.action = NC_CRYPT_CREATE;
    c.output = out;
    c.output_len = out_len;

    return nc_crypt(password, setting, &c);
}

/**
 * @brief Verify a password against a stored hash.
 *
 * @param[in] password Password.
 * @param[in] setting Complete stored hash.
 * @param[in] match_init Initial value of the match result, to check that it is always set.
 * @param[out] match Resulting match value.
 * @return nc_crypt() return value.
 */
static int
test_crypt_verify(const char *password, const char *setting, int match_init, int *match)
{
    struct nc_crypt c;
    int rc;

    memset(&c, 0, sizeof c);
    c.action = NC_CRYPT_VERIFY;
    c.match = match_init;

    rc = nc_crypt(password, setting, &c);
    *match = c.match;

    return rc;
}

/**
 * @brief Check that every reference vector is created exactly.
 *
 * @param[in] state Test state.
 */
static void
test_algo_reference(void **state)
{
    char out[NC_CRYPT_BUFSIZE];
    size_t i;

    (void)state;

    for (i = 0; i < (sizeof test_vectors / sizeof *test_vectors); ++i) {
        assert_int_equal(test_crypt_create(test_vectors[i].password, test_vectors[i].setting, out, sizeof out), 0);
        assert_string_equal(out, test_vectors[i].expected);
    }
}

/**
 * @brief Check handling of invalid arguments.
 *
 * @param[in] state Test state.
 */
static void
test_invalid_args(void **state)
{
    char out[NC_CRYPT_BUFSIZE];
    struct nc_crypt c;

    (void)state;

    /* NULL arguments */
    memset(&c, 0, sizeof c);
    c.action = NC_CRYPT_CREATE;
    c.output = out;
    c.output_len = sizeof out;
    assert_int_equal(nc_crypt(NULL, "$6$abc$", &c), -1);
    assert_int_equal(nc_crypt("hello", NULL, &c), -1);
    assert_int_equal(nc_crypt("hello", "$6$abc$", NULL), -1);

    /* no output buffer for hash creation */
    memset(&c, 0, sizeof c);
    c.action = NC_CRYPT_CREATE;
    c.output_len = sizeof out;
    assert_int_equal(nc_crypt("hello", "$6$abc$", &c), -1);
}

/**
 * @brief Check handling of a small output buffer, an unknown action, an unknown
 * hash id and a malformed hash string.
 *
 * @param[in] state Test state.
 */
static void
test_invalid_input(void **state)
{
    static const char *sha512_hello = TEST_HASH_SHA512_HELLO;
    static const char *sha256_rounds_hello = "$5$rounds=1000$abcdefghijklmnop$WrXWnj4kGA329xgo6OuYgg4dCUBFRerEyEW8GtoN6I5";
    char out[NC_CRYPT_BUFSIZE];
    struct nc_crypt c;
    int match;

    (void)state;

    /* an output buffer of the exact size works */
    assert_int_equal(test_crypt_create("hello", "$6$abcdefghijklmnop$", out, strlen(sha512_hello) + 1), 0);
    assert_string_equal(out, sha512_hello);
    assert_int_equal(test_crypt_create("hello", "$5$rounds=1000$abcdefghijklmnop$", out, strlen(sha256_rounds_hello) + 1), 0);
    assert_string_equal(out, sha256_rounds_hello);

    /* an output buffer one byte too small fails before the hash is computed and the buffer is not modified at all */
    memset(out, (char)0xAA, sizeof out);
    assert_int_equal(test_crypt_create("hello", "$6$abcdefghijklmnop$", out, strlen(sha512_hello)), -4);
    assert_int_equal(out[0], (char)0xAA);
    assert_int_equal(out[strlen(sha512_hello) / 2], (char)0xAA);
    assert_int_equal(out[sizeof out - 1], (char)0xAA);

    /* unknown action */
    memset(&c, 0, sizeof c);
    c.action = (enum nc_crypt_action)42;
    assert_int_equal(nc_crypt("hello", "$6$abc$", &c), -1);

    /* unknown hash id */
    assert_int_equal(test_crypt_create("hello", "$2b$abcdefghijklmnop$", out, sizeof out), -2);
    assert_int_equal(test_crypt_create("hello", "$2y$abcdefghijklmnop$", out, sizeof out), -2);
    assert_int_equal(test_crypt_create("hello", "$7$abc$", out, sizeof out), -2);
    assert_int_equal(test_crypt_create("hello", "$x$abc$", out, sizeof out), -2);
    assert_int_equal(test_crypt_create("hello", "$0$password", out, sizeof out), -2);
    assert_int_equal(test_crypt_create("hello", "$6abc$", out, sizeof out), -2);
    assert_int_equal(test_crypt_verify("hello", "$2b$abcdefghijklmnop$hash", 0, &match), -2);

    /* malformed setting string */
    assert_int_equal(test_crypt_create("hello", "", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$6", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "6$abc$", out, sizeof out), -3);

    /* salt characters outside the crypt base64 alphabet [a-zA-Z0-9./] */
    assert_int_equal(test_crypt_create("hello", "$6$a!b@c#$", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$1$a!b@c#$", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$6$ab cd$", out, sizeof out), -3);
    /* crypt_r(3) tolerates '=' in a "$1$" salt, but the iana-crypt-hash
     * YANG type excludes it as well */
    assert_int_equal(test_crypt_create("hello", "$1$rounds=5$", out, sizeof out), -3);
    /* the whole salt run is validated, even past the truncation length */
    assert_int_equal(test_crypt_create("hello", "$6$abcdefghijklmnop!xyz$", out, sizeof out), -3);
    /* invalid characters in the stored digest of a verification */
    assert_int_equal(test_crypt_verify("hello", "$6$abcdefghijklmnop$vRqpf9WzVv13MKJy4hd5!ALhNQnt4y0RZsj0MrdHWdwA8G8gihD6oj69IwfuemaVekHG0M6jA5HNgthaIaLRR/", 0, &match), -3);
    assert_int_equal(match, 1);

    /* invalid "rounds=" specification */
    assert_int_equal(test_crypt_create("hello", "$5$rounds=abc$abc$", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$5$rounds=$abc$", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$5$rounds=1x$abc$", out, sizeof out), -3);

    /* "rounds=" out of the valid range [1000, 999999999] */
    assert_int_equal(test_crypt_create("hello", "$5$rounds=0$abc$", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$5$rounds=999$abc$", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$5$rounds=1000000000$abc$", out, sizeof out), -3);
    assert_int_equal(test_crypt_create("hello", "$6$rounds=99999999999999999999$abc$", out, sizeof out), -3);

    /* no stored digest to verify against */
    assert_int_equal(test_crypt_verify("hello", "$6$abcdefghijklmnop$", 0, &match), -3);
    assert_int_equal(match, 1);
}

/**
 * @brief Check password verification against stored hashes.
 *
 * @param[in] state Test state.
 */
static void
test_verify_password(void **state)
{
    int match;

    (void)state;

    /* correct password of every scheme */
    assert_int_equal(test_crypt_verify("hello", "$1$abcdefgh$rwnEbRiN0agqVgZBovWNQ/", 1, &match), 0);
    assert_int_equal(match, 0);
    assert_int_equal(test_crypt_verify("hello", "$5$rounds=10000$abcdefghijklmnop$gakfHbxNcYmu8/VVGCdhagYkdMmRhzRqQyQhHYWi9k7", 1, &match), 0);
    assert_int_equal(match, 0);
    assert_int_equal(test_crypt_verify("hello", TEST_HASH_SHA512_HELLO, 1, &match), 0);
    assert_int_equal(match, 0);

    /* empty password */
    assert_int_equal(test_crypt_verify("", "$1$$qRPK7m23GJusamGpoGLby/", 1, &match), 0);
    assert_int_equal(match, 0);

    /* wrong password */
    assert_int_equal(test_crypt_verify("hellp", TEST_HASH_SHA512_HELLO, 0, &match), 0);
    assert_int_equal(match, 1);
    assert_int_equal(test_crypt_verify("", TEST_HASH_SHA512_HELLO, 0, &match), 0);
    assert_int_equal(match, 1);
}

/**
 * @brief Check handling of unusual salt formats.
 *
 * @param[in] state Test state.
 */
static void
test_salt_format(void **state)
{
    char out[NC_CRYPT_BUFSIZE];
    int match;

    (void)state;

    /* a '$' in the setting terminates the salt, the rest is the stored digest */
    assert_int_equal(test_crypt_create("hello", "$6$ab$cd$", out, sizeof out), 0);
    assert_string_equal(out, "$6$ab$kCEdajKfECjkWwo5i4GMTY4WW.ADIevHyGdlZb3r8wskFWlOJqWZgemJ96NLPhkdsWWH5zZrOY6OzTC0hpeuU1");

    /* empty salt round-trip */
    assert_int_equal(test_crypt_create("hello", "$6$$", out, sizeof out), 0);
    assert_int_equal(test_crypt_verify("hello", out, 1, &match), 0);
    assert_int_equal(match, 0);
}

/**
 * @brief Check verification against corrupted stored hashes.
 *
 * @param[in] state Test state.
 */
static void
test_corrupt_stored_hash(void **state)
{
    char buf[NC_CRYPT_BUFSIZE];
    int match;

    (void)state;

    /* truncated digest */
    strcpy(buf, TEST_HASH_SHA512_HELLO);
    buf[strlen(buf) - 1] = '\0';
    assert_int_equal(test_crypt_verify("hello", buf, 0, &match), 0);
    assert_int_equal(match, 1);

    /* extended digest */
    strcpy(buf, TEST_HASH_SHA512_HELLO);
    strcat(buf, "x");
    assert_int_equal(test_crypt_verify("hello", buf, 0, &match), 0);
    assert_int_equal(match, 1);

    /* corrupted digest character */
    strcpy(buf, TEST_HASH_SHA512_HELLO);
    buf[60] = (buf[60] == 'A') ? 'B' : 'A';
    assert_int_equal(test_crypt_verify("hello", buf, 0, &match), 0);
    assert_int_equal(match, 1);

    /* character outside the base64 alphabet in the digest */
    strcpy(buf, TEST_HASH_SHA512_HELLO);
    buf[25] = '!';
    assert_int_equal(test_crypt_verify("hello", buf, 0, &match), -3);
    assert_int_equal(match, 1);

    /* no digest at all */
    assert_int_equal(test_crypt_verify("hello", "$6$abcdefghijklmnop$", 0, &match), -3);
    assert_int_equal(match, 1);
}

int
main(void)
{
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(test_algo_reference),
        cmocka_unit_test(test_invalid_args),
        cmocka_unit_test(test_invalid_input),
        cmocka_unit_test(test_verify_password),
        cmocka_unit_test(test_salt_format),
        cmocka_unit_test(test_corrupt_stored_hash),
    };

    return cmocka_run_group_tests(tests, NULL, NULL);
}
